name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt --check
    - name: clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test -r --verbose
